services:
  password-generator:
    image: ghcr.io/main-roads/passwordgeneratorxkcd:${DOCKER_TAG:-latest}
    container_name: password-generator
    restart:  unless-stopped
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    # volumes:
    #   - ./config.yaml:/home/xkcd/web/project/config.yaml:ro
    read_only: true
    tmpfs:
      - /tmp