APP:
  DEBUG: false
  HOST: 0.0.0.0
  MINIFY_HTML: true
XKCDPASS:
  wordfile: null
  numwords: 4
  min_length: 4
  max_length: 7
  acrostic: null
  valid_chars: .
  verbose: false
  delimiter: null
  random_delimiters: true
  valid_delimiters: " ,."
  case_methods: capitalize
  count: 25
