version: "3.8"

services:
  web:
    container_name: password-generator-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    read_only: true
    tmpfs:
      - /tmp
  nginx:
    container_name: password-generator
    restart: always
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 8080:80
    read_only: true
    depends_on:
      - web
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

volumes:
  static_volume:
