upstream xkcd_generator_flask {
    server web:5000;
}
server {

    listen 80;
    access_log  off;
    client_body_timeout 5s;
    client_header_timeout 5s;
    client_body_buffer_size 200K;
    client_header_buffer_size 2k;
    client_max_body_size 200k;
    large_client_header_buffers 3 1k;

    location / {
        proxy_pass http://xkcd_generator_flask;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /home/app/web/project/static/;
    }

}
