#version: "3.8"

services:
  password-generator:
    image: ghcr.io/main-roads/passwordgeneratorxkcd:dev
    pull_policy: never
    container_name: xkcd-build
    restart: never
    build:
      context: .
      args:
        APPUSER: ${APPUSER:-xkcd}
        APPGROUP: ${APPGROUP:-xkcd}
        PORT_ARG: ${PORT:-5000}
      dockerfile: Dockerfile
    expose:
      - ${PORT:-5000}

networks:
  default:
   name: xkcd-build